//
//  Copyright 2019 - 2021 XiaoJSoft Studio. All rights reserved.
//  Use of this source code is governed by a BSD-style license that can be
//  found in the LICENSE.md file.
//

//
//  Constants.
//

//  Modbus exception codes.
const MBEX_ILLEGAL_FUNCTION = 0x01;
const MBEX_ILLEGAL_DATA_ADDRESS = 0x02;
const MBEX_ILLEGAL_DATA_VALUE = 0x03;
const MBEX_SERVER_DEVICE_FAILURE = 0x04;
const MBEX_ACKNOWLEDGE = 0x05;
const MBEX_SERVER_DEVICE_BUSY = 0x06;
const MBEX_MEMORY_PARITY_ERROR = 0x08;
const MBEX_GW_PATH_UNAVAILABLE = 0x0A;
const MBEX_GW_TARGET_FAILED = 0x0B;

//  Export public APIs.
module.exports = {
    "MBEX_ILLEGAL_FUNCTION": MBEX_ILLEGAL_FUNCTION,
    "MBEX_ILLEGAL_DATA_ADDRESS": MBEX_ILLEGAL_DATA_ADDRESS,
    "MBEX_ILLEGAL_DATA_VALUE": MBEX_ILLEGAL_DATA_VALUE,
    "MBEX_SERVER_DEVICE_FAILURE": MBEX_SERVER_DEVICE_FAILURE,
    "MBEX_ACKNOWLEDGE": MBEX_ACKNOWLEDGE,
    "MBEX_SERVER_DEVICE_BUSY": MBEX_SERVER_DEVICE_BUSY,
    "MBEX_MEMORY_PARITY_ERROR": MBEX_MEMORY_PARITY_ERROR,
    "MBEX_GW_PATH_UNAVAILABLE": MBEX_GW_PATH_UNAVAILABLE,
    "MBEX_GW_TARGET_FAILED": MBEX_GW_TARGET_FAILED
};